// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFavorite(arg1) {
  return window['go']['main']['App']['AddFavorite'](arg1);
}

export function AddFavoriteItem(arg1) {
  return window['go']['main']['App']['AddFavoriteItem'](arg1);
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function ExecuteTool(arg1) {
  return window['go']['main']['App']['ExecuteTool'](arg1);
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Health() {
  return window['go']['main']['App']['Health']();
}

export function ListFavorites() {
  return window['go']['main']['App']['ListFavorites']();
}

export function ListTools() {
  return window['go']['main']['App']['ListTools']();
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function RemoveFavorite(arg1) {
  return window['go']['main']['App']['RemoveFavorite'](arg1);
}

export function RemoveFavoriteItem(arg1) {
  return window['go']['main']['App']['RemoveFavoriteItem'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SearchTools(arg1) {
  return window['go']['main']['App']['SearchTools'](arg1);
}

export function SelectDocumentFile() {
  return window['go']['main']['App']['SelectDocumentFile']();
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SelectOutputDirectory() {
  return window['go']['main']['App']['SelectOutputDirectory']();
}
export function Workbench(action, payload) {
  return window['go']['main']['App']['Workbench'](action, payload);
}
