// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddFavorite(arg1:string):Promise<void>;

export function AddFavoriteItem(arg1:models.Favorite):Promise<models.Favorite>;

export function ClearHistory():Promise<void>;

export function ExecuteTool(arg1:models.ToolInput):Promise<models.ToolOutput>;

export function GetHistory():Promise<Array<models.History>>;

export function Greet(arg1:string):Promise<string>;

export function Health():Promise<Record<string, any>>;

export function ListFavorites():Promise<Array<models.Favorite>>;

export function ListTools():Promise<Array<models.Tool>>;

export function LoadSettings():Promise<models.Settings>;

export function RemoveFavorite(arg1:string):Promise<void>;

export function RemoveFavoriteItem(arg1:string):Promise<void>;

export function SaveSettings(arg1:models.Settings):Promise<void>;

export function SearchTools(arg1:string):Promise<Array<models.Tool>>;

export function SelectFile():Promise<string>;
